import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  OneToMany,
  JoinColumn,
  Index,
} from 'typeorm';
import { AuthorApplication } from './user.entity';

export enum BookStatus {
  DRAFT = 'draft',
  PENDING_REVIEW = 'pending_review',
  PUBLISHED = 'published',
  OFFLINE = 'offline',
  DELETED = 'deleted',
}

export enum PriceStrategy {
  FREE = 'free',
  PAY_PER_CHAPTER = 'pay_per_chapter',
  PAY_FULL_BOOK = 'pay_full_book',
  VIP_ONLY = 'vip_only',
}

@Entity('books')
export class Book {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  @Index()
  authorId: string;

  @ManyToOne(() => AuthorApplication)
  @JoinColumn({ name: 'authorId' })
  author: AuthorApplication;

  @Column()
  title: string;

  @Column({ nullable: true })
  originalTitle: string;

  @Column({ type: 'text', nullable: true })
  description: string;

  @Column({ nullable: true })
  cover: string;

  @Column({ nullable: true })
  coverLarge: string;

  @Column({ type: 'enum', enum: BookStatus, default: BookStatus.DRAFT })
  @Index()
  status: BookStatus;

  @Column({ type: 'enum', enum: PriceStrategy, default: PriceStrategy.FREE })
  priceStrategy: PriceStrategy;

  @Column({ type: 'decimal', precision: 10, scale: 2, default: 0 })
  fullBookPrice: number;

  @Column({ default: 0 })
  totalChapters: number;

  @Column({ default: 0 })
  publishedChapters: number;

  @Column({ default: 0 })
  totalWords: number;

  @Column({ default: 0 })
  totalViews: number;

  @Column({ default: 0 })
  totalLikes: number;

  @Column({ default: 0 })
  totalCollections: number;

  @Column({ default: 0 })
  totalReviews: number;

  @Column({ type: 'decimal', precision: 3, scale: 2, default: 0 })
  avgRating: number;

  @Column({ nullable: true })
  language: string;

  @Column({ nullable: true })
  tags: string; // JSON array

  @Column({ nullable: true })
  categories: string; // JSON array

  @Column({ nullable: true })
  publisher: string;

  @Column({ nullable: true })
  publishDate: Date;

  @Column({ nullable: true })
  isbn: string;

  @Column({ nullable: true })
  pdfUrl: string;

  @Column({ nullable: true })
  pdfOriginalName: string;

  @Column({ nullable: true })
  toc: string; // Table of contents JSON

  @Column({ nullable: true })
  metadata: string; // Additional metadata JSON

  @Column({ nullable: true })
  seoTitle: string;

  @Column({ nullable: true })
  seoDescription: string;

  @Column({ default: true })
  isFeatured: boolean;

  @Column({ default: false })
  isCompleted: boolean;

  @Column({ nullable: true })
  lastChapterAt: Date;

  @Column({ nullable: true })
  @Index()
  publishedAt: Date;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}

@Entity('chapters')
export class Chapter {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  @Index()
  bookId: string;

  @ManyToOne(() => Book)
  @JoinColumn({ name: 'bookId' })
  book: Book;

  @Column()
  @Index()
  authorId: string;

  @Column()
  chapterNumber: number;

  @Column()
  title: string;

  @Column({ type: 'text', nullable: true })
  content: string;

  @Column({ nullable: true })
  summary: string;

  @Column({ nullable: true })
  wordCount: number;

  @Column({ nullable: true })
  coverImage: string;

  @Column({ type: 'decimal', precision: 10, scale: 2, default: 0 })
  price: number;

  @Column({ default: true })
  isVipChapter: boolean;

  @Column({ default: false })
  isFreePreview: boolean;

  @Column({ default: false })
  isAutoGenerated: boolean;

  @Column({ type: 'enum', enum: ['draft', 'published', 'hidden'], default: 'draft' })
  status: string;

  @Column({ nullable: true })
  publishedAt: Date;

  @Column({ nullable: true })
  views: number;

  @Column({ nullable: true })
  likes: number;

  @Column({ nullable: true })
  order: number;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}

@Entity('book_categories')
export class BookCategory {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  name: string;

  @Column({ nullable: true })
  nameEn: string;

  @Column({ nullable: true })
  description: string;

  @Column({ nullable: true })
  icon: string;

  @Column({ nullable: true })
  cover: string;

  @Column({ default: 0 })
  sortOrder: number;

  @Column({ default: true })
  isActive: boolean;

  @Column({ nullable: true })
  parentId: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}

@Entity('book_tags')
export class BookTag {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ unique: true })
  name: string;

  @Column({ nullable: true })
  nameEn: string;

  @Column({ default: 0 })
  usageCount: number;

  @CreateDateColumn()
  createdAt: Date;
}

@Entity('book_collections')
export class BookCollection {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  @Index()
  userId: string;

  @Column()
  @Index()
  bookId: string;

  @Column({ nullable: true })
  note: string;

  @CreateDateColumn()
  createdAt: Date;
}
